packages:
  - "01-databases-real-world"
  - "02-nosql-intro"
  - "03-document-oriented-db"
  - "04-mongodb-data-structures"
  - "05-mongodb-aggregation"
  - "06-mongodb-sharding-replication"
  - "07-mongodb-indexing"
  - "08a-modeling-inheritance-computed-approximation"
  - "08b-modeling-reference-versioning-single-collection"
  - "08c-modeling-subset"
  - "09-dynamodb-intro"
  - "10-dynamodb-data-modeling"
  - "11-dynamodb-design-patterns"
